@startuml conc_detaillee_robot

actor user as user1
actor user as user2
actor simulateurRobot

folder CommandoV3 <<folder>> {
    rectangle "<u>robot:Robot</u>" <<protected>> as robot
    rectangle "<u>adminUI:AdminUI</u>" <<active>> as adminUI
    rectangle "<u>pilot:Pilot</u>" <<active>> as pilot
    rectangle "<u>logger:Logger</u>" <<active>> as logger
}

folder TelcoV3 <<folder>> {
    rectangle "<u>remoteUI:RemoteUI</u>" <<active>> as remoteUI
}

user1 -- adminUI : \
    toggleEmergencyStop() <&arrow-thick-bottom> \n\
    quit() <&arrow-thick-bottom> \n\
    goScreenLog() <&arrow-thick-bottom> \n\
    clearLog() <&arrow-thick-bottom> \n\
    backMainScreen() <&arrow-thick-bottom> \n\
    displayScreen(idScreen) <&arrow-thick-top>

user2 -- remoteUI : \
    toggleEmergencyStop() <&arrow-thick-bottom> \n\
    quit() <&arrow-thick-bottom> \n\
    goScreenLog() <&arrow-thick-bottom> \n\
    backMainScreen() <&arrow-thick-bottom> \n\
    displayScreen(idScreen) <&arrow-thick-top> \n\
    setDir(dir) <&arrow-thick-bottom> \n\
    setIp(ip) <&arrow-thick-bottom> \n\
    validate() <&arrow-thick-bottom>

robot -- simulateurRobot : voir doc infox

adminUI -- pilot : toggleES() <&arrow-thick-bottom>
adminUI -- logger : \
    getEvents(from,to):Event[] <&arrow-thick-bottom> \n\
    getEventsCount():Indice <&arrow-thick-bottom> \n\
    clearEvents() <&arrow-thick-bottom> \n\
    startPolling() <&arrow-thick-bottom> \n\
    stopPolling() <&arrow-thick-bottom>

pilot -- robot :\
    setWheelsVelocity(wvr,wvl) <&arrow-thick-bottom> \n\
    getSensorsState():SensorsState <&arrow-thick-bottom>

pilot -- logger : signalES() <&arrow-thick-bottom>

logger -- robot : \
    getSensorsState():SensorsState <&arrow-thick-bottom> \n\
    getRobotSpeed():Speed <&arrow-thick-bottom>

remoteUI -- pilot : \
    setVelocity(vel) <&arrow-thick-bottom> \n\
    toggleES() <&arrow-thick-bottom>

remoteUI -- logger : \
    getEvents(from,to):Event[] <&arrow-thick-bottom> \n\
    getEventsCount():Indice <&arrow-thick-bottom>



@enduml
